
kookyemount.blend

todo:
  slice stem into rectangle
  drill hole in stem for spring
  slide stem 8mm towards center
  trim bottom point of stem to fit into girder V
  cut V in back wall for girder
  make indentation in stem for girder screw
  shave down top edge of back wall and stem

MPU-6050 orientation and polarity of 3 axes
https://how2electronics.com/wp-content/uploads/2018/06/2_Oreintation_Polarity_of_Rotation_MPU6050.png

Two different axes systems.
1. in the MPU-6050
	x is the direction of travel, +forward, -reverse;  roll +right, -left 
	y is axial, +left, -right; pitch +nose up, -nose down
	z is vertical, +up, -down; yaw +nose left, -nose right 

2. in blender
	x red, runs across the screen right to left
	y green, runs towards and away from the viewer
	z blue, is vertical

Two different view sets.
1. The Blender model is relative to the mount, and using the MPU-6050 axes.
	front = right side of vehicle, looking into the jaws of the mount
	back = left side of vehicle
	left = rear of vehicle
	right = front of vehicle

2. The GIMP drawing is equivalent to the Blender right view.



dimensions, location, rotation - see spreadsheet

The drawing is centered on the motor, dimensions 40x40x20.
The motor is lying down, so the z dimension is 20.
The y dimension is 40, the direction of the axle or rotor.
The x dimension is 40, the direction of travel.
The rotor shaft is offset by 10mm so that 30mm extends from the shaft towards the front,
and 10mm extends towards the rear.

The motor has two flange/grommets for mounting, one front one rear.
The flange/grommets are placed so that 13mm will extend in front of the mount, and 27mm behind.
Each flange grommet contains two screw holes, aligned with the y axis.
The motor also has a cable coming out from rear side, near the back of the motor.

motor screw holes
	motor screw holes (4) 2M x 6mm in the flange/grommets
	distance between z = 10mm
	distance between x = 50mm
	pilot holes in the mount: 1.5mm x 10mm
	rotate on x axis: 90	

cable hole
	x = 8mm (clear thru the sidewall)
	y = 6mm  (19-25mm from front)
	z = 7mm (centered within 20mm sidewall)
	z with extension = 7 + ((20-7)/2) = 7 + 6.5 = 13.5
	z loc = (20 - 13.5)/2 = 3.25

stem
x = 14mm     width, width of the axle girder
y = 16mm     length 15 external plus 1mm extruded into the mount for boolean union operation
z = 12.5mm   height of the axle girder, 9mm height of stem to leave room for truck rotation 

stem will be rotated 45 degrees to match the axle girder
stem cutouts and mount cutouts will be rotated simultaneously

stem cutouts
  stem bolt hole
  stem indentation for recessed nut
  stem spring hole

mount cutouts
  girder slice right - 1mm out of mount back wall
  girder slice left - 1mm

all above to stem rotated around the rotor on the y axis by 45 degr

position of the rear drive wheel => half length of rear axle => determined by y dimensions of:
+ rotor gear extension y  = 14mm
+ mount y
 - girder slice       1mm
+ plus stem y    19mm

bolt hole y = 
distance from girder end to bolt hole
less 1mm girder slice

5.5 holes of girder between tire and truck post
5.5 * 12.7 in = 69.85, round up to 70mm

70mm from center point to inside tire wall
breakdown of y distances:
  2mm - space between tire motor
13mm - motor in front of mount  
27mm - motor inside of mount
  1mm - space around motor
  6mm - back wall of mount
 -1mm - incision for girder insert
 25.4mm - girder
 
 70mm - total   73.4     4mm over
 
motor dimensions: 40x40x20
space around 3 sides of motor: 1mm
motor hole: 42x28x20
mount sides: 8mm
mount back: 6mm
mount dimensions: 50x34x20


y dimensions of motor
40mm - motor y front to back
  7mm - flange/grommet to front of motor
  6mm - flange-grommet
27mm - flange/grommet to back of motor

motor under flange: 40x27x20mm


41 - 27 = 14 mm rotor extension  

motor: 20x40x40
motor x = 40
motor y = 40
motor z = 20m

motor y = 40mm
plus 1mm space between tirewall
plus 1mm space between mount
total 42 from mount to tire

69 - 42 = 27

grid = .5in = 12.7mm
girder bolt hole = 69 - 12.7mm = 56.3 



final sculpting
  stem cutouts
  rotate stem and V slices (see "rotate stem..." below)
  mount cutouts
  union mount and stem

export only the mount union


rotate stem and Vslices around y axis of rotor
  select rotor
  shift-s, cursor to selected
  in header, Transform Pivot Point menu, choose 3D Cursor
  select all the objects to be rotated together
  r y 45 <enter>



